### ISSUE TITLE
some problem (no support for secondary objectives)

### ISSUE THREAD

**Issue by nodejs126123** [JeroenGar/gdrr-2bp#1]
HI
when I use your library.i have some problems
https://github.com/JeroenGar/gdrr-2bp/blob/0d7a46dba4ab9d591e7ad8c5eae79fe3c4c905c6/src/io/json_format.rs#L30
The meaning of these fields
The code has no comments and no reference to the dataset. I have no idea how to use it.  if i can use it,I'd like to pay a fee What's your email address?
thanks

**Comment by JeroenGar** [comment]
Hello, this most likely means something is wrong with the input file you supplied. Can you upload the input JSON file? And the exact error output.

**Comment by nodejs126123** [comment]
> 您好，这很可能意味着您提供的输入文件有问题。您可以上传输入的 JSON 文件吗？以及确切的错误输出。

this is a set data of rectangles.
const widths = [290, 340, 340, 490, 490, 490, 390, 590, 490, 490, 490, 590, 690, 690, 690, 690, 690, 290, 690, 890, 890]; const heights = [290, 990, 990, 390, 390, 390, 990, 490, 590, 590, 590, 690, 590, 590, 590, 590, 590, 690, 490, 490, 690];
this is container size width=1480 height=4000
the container's size is fixed,count is not fixed.when last container is overflow.then place into next container.
The horizontal direction can be cut, and the remaining height of the last container is the largest and most optimized.
thanks. 
my email: tms063840@gmail.com

**Comment by JeroenGar** [comment]
You have to ensure the input JSON is in the correct structure. All information regarding the input file can be found here: [https://github.com/JeroenGar/gdrr-2bp?tab=readme-ov-file#input-json](https://github.com/JeroenGar/gdrr-2bp?tab=readme-ov-file#input-json)

Let me know if you have any specific questions.

**Comment by nodejs126123** [comment]
> 您必须确保输入的 JSON 具有正确的结构。有关输入文件的所有信息都可以在这里找到：[https ://github.com/JeroenGar/gdrr-2bp?tab=readme-ov-file#input-json](https://github.com/JeroenGar/gdrr-2bp?tab=readme-ov-file#input-json)
> 
> 如果您有任何具体问题请告诉我。

Based on the current test results, the outcome is not sufficiently optimized. Just need a bin.but it used two bins

**Comment by JeroenGar** [comment]
Please provide a reproducible example for me to test.

**Comment by nodejs126123** [comment]
> 请提供一个可重现的示例供我测试。

const widths = [290, 340, 340, 490, 490, 490, 390, 590, 490, 490, 490, 590, 690, 690, 690, 690, 690, 290, 690, 890, 890]; const heights = [290, 990, 990, 390, 390, 390, 990, 490, 590, 590, 590, 690, 590, 590, 590, 590, 590, 690, 490, 490, 690];
this is bin size width=1480 height=4000  you use this data to test. Send me the results then.thank you

**Comment by JeroenGar** [comment]
I am not going to manually convert this. You either provide me a JSON input file of your data, or I close this issue.

**Comment by nodejs126123** [comment]
> 我不会手动转换它。你要么给我一个包含你数据的 JSON 输入文件，要么我关闭这个问题。

[input.json](https://github.com/user-attachments/files/17816014/input.json)

**Comment by nodejs126123** [comment]
> > 我不会手动转换它。你或者给我一个包含你数据的 JSON 输入文件，或者我关闭这个问题。
> 
> [输入.json](https://github.com/user-attachments/files/17816014/input.json)

I need a guillotine to cut horizontally, that is, in the 1480 direction.

**Comment by JeroenGar** [comment]
> [input.json](https://github.com/user-attachments/files/17816014/input.json)

This file contains totally different measurements than those you provided earlier? For this file the algorithm easily finds a solution using a single bin.

Fixing the initial orientation of saw is currently unsupported.
This repo is mainly targeted at the academic version of the problem.

However, it should be easy to add support for that.

**Comment by nodejs126123** [comment]
[input (2).json](https://github.com/user-attachments/files/17816503/input.2.json)

**Comment by JeroenGar** [comment]
> [input (2).json](https://github.com/user-attachments/files/17816503/input.2.json)

The items in this instance add up to **>116%** of the area of a single bin:
`[00:00:00]	[T0]	<complete>	(usage: 58.312%, p_incl: 100.000%, sheets: 2, mat: 11840000)`

It is impossible to fit these items into a single bin.

**Comment by nodejs126123** [comment]
I see,run your program  fit these items into two bins.but it is not optimized

**Comment by nodejs126123** [comment]
> 我明白了，运行你的程序将这些项目放入两个箱子中。但它没有优化
I hope it can leave more blank space in the vertical direction.

**Comment by JeroenGar** [comment]
This repo is targeted at the **academic** 2D bin packing problem.
The only objective is to minimize the value of bins required to include all the items.

In its current form, no secondary objectives (like "blank space in the vertical direction") are included.
However, you are free to fork this repo and add support for the secondary objectives you desire.
This should only require slight changes to the existing algorithm.
